### ISSUE TITLE
Обновление UI авториазции битрикса сломало библиотеку

### ISSUE THREAD

**Issue by opravdin** [xUJYx/bitrix24_api_authorization#1]
Разработчики битрикса обновили интерфейс авторизации, поэтому скрипт валится с ошибкой "ERROR IN GETTING BITRIX AUTH BACKURL"
Как воспроизвести:
Попытаться авторизоваться на любом обновившемся портале б24

**Comment by xUJYx** [comment]
> Разработчики битрикса обновили интерфейс авторизации, поэтому скрипт валится с ошибкой "ERROR IN GETTING BITRIX AUTH BACKURL"
> Как воспроизвести:
> Попытаться авторизоваться на любом обновившемся портале б24

Да, проблема существет... Причём обновили таким образом, что решить проблему пока не удалось, но работы в этом направлении уже ведутся...

**Comment by opravdin** [comment]
Переписал частично в форке https://github.com/opravdin/bitrix24_api_authorization

**Comment by xUJYx** [comment]
Крсавчик, спасибо за правки!..
